name: github-profile-toolbox
description: Add a toolbox in your profile's README
author: alexandre-abrioux
branding:
  color: purple
  icon: tool
inputs:
  config:
    description: path to the YAML configuration file
    default: .github/github-profile-toolbox.yml
    required: false
  readme:
    description: path to the README file that should be modified
    default: README.md
    required: false
runs:
  using: docker
  image: ghcr.io/alexandre-abrioux/github-profile-toolbox:latest
  args:
    - --config=${{ inputs.config }}
    - --readme=${{ inputs.readme }}